#Refs:
# 1. https://github.com/nukc/how-to-use-travis-ci
# 2. https://docs.travis-ci.com/user/languages/android/


language: android
dist: trusty

notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置 false 吧
  email: false

before_install:     
 - chmod +x gradlew  # 改变 gradlew 的访问权限

script:              # 执行:下面的命令
  - ./gradlew assembleRelease  

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-26
    # - sys-img-armeabi-v7a-android-17